name: Maven Package and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}/flatner/

    - name: List files in directory
      run: ls -la ${{ github.workspace }}/flatner/

    - name: Eliminar artefacto anterior
      run: rm -f ${{ github.workspace }}/flatner/target/*.jar


    - name: Build with Maven
      run: mvn -B clean package --file ${{ github.workspace }}/flatner/pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allartifacts
        path: /home/saul/DAM/saul_flatner_ppp/flatner/target/*
        
    - name: Upload to remote with SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        username: ${{ secrets.SSH_USERNAME }}
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.KEY }}
        source: "flatner/target/*.jar"
        target: "~/"
        overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          docker stop flatner-container;
          docker rm flatner-container;
          docker rmi flatner;
          docker compose up -d

