name: Maven Package and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: List files in directory
      run: ls -la ${{ github.workspace }}/flatner/


    - name: Build with Maven
      run: mvn -B clean package --file ${{ github.workspace }}/flatner/pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allartifacts
        path: /home/saul/DAM/saul_flatner_ppp/flatner/target/*

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: allartifacts
        path: target

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.3.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          # Detener la aplicación si está en ejecución
          sudo systemctl stop my-application.service || true
          
          # Eliminar la versión anterior de la aplicación
          sudo rm -rf /opt/my-application/*
          
          # Descomprimir el archivo JAR en el directorio de despliegue
          mkdir -p /opt/my-application
          tar -xf target/*.tar.gz -C /opt/my-application
          
          # Iniciar la aplicación
          sudo systemctl start my-application.service
